name: core-linux
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      
      - name: configure OS
        run: |
          # os level stuff
          pwd
          ls
          set -x
          export DEBIAN_FRONTEND="noninteractive"
          export TZ="America/Los_Angeles"
          sudo apt-get update -qq
          sudo apt-get install -qq -y git-core gcc g++ \
            gfortran cmake subversion automake  m4 \
            libgtest-dev libmkl-dev libopenblas-openmp-dev
      
      - name: install BLAS++
        run: |
          cd ..
          pwd
          ls
          git clone https://bitbucket.org/icl/blaspp.git
          mkdir blaspp-build
          cd blaspp-build
          pwd
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/../blaspp-install -Dbuild_tests=OFF ../blaspp
          make -j2 install

      - name: install Random123  
        run: |
          cd ..
          pwd
          ls
          git clone https://github.com/DEShawResearch/Random123.git
          cd Random123/
          make prefix=`pwd`/../Random123-install install-include

      - name: build RandBLAS
        run: |
          cd ..
          pwd
          ls
          mkdir RandBLAS-build
          cd RandBLAS-build
          cmake -DCMAKE_BUILD_TYPE=Release \
            -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp/ \
            -DRandom123_DIR=`pwd`/../Random123-install/include/ \
            -DCMAKE_INSTALL_PREFIX=`pwd`/../RandBLAS-install \
            -DCMAKE_BINARY_DIR=`pwd` \
            `pwd`/../RandBLAS
          make -j2 install
          ctest --output-on-failure
