name: openmp-macos
on:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      
      - name: configure OS
        run: |
          # os level stuff
          pwd
          ls
          set -x
          brew install googletest
          # install OpenMP
          export tmp_dir=`pwd`
          cd /usr/local/Cellar/libomp/
          #   there should only be one subdirectory
          cd */
          export libomp_dir=`pwd`
          echo ${libomp_dir}
          ls
          export CXXFLAGS=-I${libomp_dir}/include
          echo $CXXFLAGS
          export LDFLAGS=-L${libomp_dir}/lib
          echo $LDFLAGS
          #   change back to where we started
          cd ${tmp_dir}
      
      - name: install BLAS++
        run: |
          cd ..
          pwd
          ls
          git clone https://bitbucket.org/icl/blaspp.git
          mkdir blaspp-build
          cd blaspp-build
          pwd
          cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=`pwd`/../blaspp-install -Dbuild_tests=OFF ../blaspp
          make -j2 install

      - name: install Random123  
        run: |
          cd ..
          pwd
          ls
          git clone https://github.com/DEShawResearch/Random123.git
          cd Random123/
          mkdir -p `pwd`/../Random123-install/include
          cp -rp include/Random123 `pwd`/../Random123-install/include/

      - name: build and test RandBLAS (release)
        run: |
          cd ..
          pwd
          ls
          mkdir RandBLAS-build
          cd RandBLAS-build
          cmake -DCMAKE_BUILD_TYPE=Release \
            -Dblaspp_DIR=`pwd`/../blaspp-install/lib/blaspp/ \
            -DRandom123_DIR=`pwd`/../Random123-install/include/ \
            -DCMAKE_INSTALL_PREFIX=`pwd`/../RandBLAS-install \
            -DCMAKE_BINARY_DIR=`pwd` \
            -DCMAKE_CXX_COMPILER=`brew --prefix llvm@15`/bin/clang \
            `pwd`/../RandBLAS
          make -j2 install
          ctest --output-on-failure
